FROM node:18-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY next.config.ts ./

# Variables de entorno
ENV NEXT_PUBLIC_BACKEND_URL=http://34.95.152.245:443/api

# Cloudinary
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dfyqhk4g6
ENV CLOUDINARY_URL=cloudinary://926583119889168:Yzd5AeY-Z14EyXe_-enRcrjdjok@dfyqhk4g6
ENV CLOUDINARY_API_SECRET=Yzd5AeY-Z14EyXe_-enRcrjdjok
ENV NEXT_PUBLIC_CLOUDINARY_API_KEY=926583119889168

# Stripe
ENV STRIPE_SECRET_KEY=sk_test_51NUxNAE8eiHCQU5rcRB7steaLxr7oaffQXrHmqOlFNKsIKvqojWQCLOOtZZRN9q8itJosnAkXDetMXp7jLlv3jjA00kFcIcc3V
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51NUxNAE8eiHCQU5ramdYezO7F5IAC5BMexjZwxUvoA81upmeReMJHKgDNm1vYkmpwfDXao1JdYWr4fgy7O0fLPVd00W1Ben3Zh

###

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm install ts-node --save-dev

RUN npm run build:config

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]