apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  template:
    metadata:
      labels:
        app: orders-ms
    spec:
      containers:
        - name: orders-ms
          image: gcr.io/wired-climate-442121-i1/orders-ms:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: env-orders-ms-config
          resources:  
            requests:  
              memory: "128Mi"  
              cpu: "100m"      
            limits:    
              memory: "256Mi"  
              cpu: "200m"     
---
apiVersion: v1
kind: Service
metadata:
  name: orders-ms-service
spec:
  type: ClusterIP
  selector:
    app: orders-ms
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-orders-ms-config
data:
  ORDER_PORT: "3005"
  ORDER_HOST: "0.0.0.0"
  DATABASE_URL_USER: postgresql://appsdb_owner:DkY8uORBLC7N@ep-blue-sea-a5lcg70b.us-east-2.aws.neon.tech/orders_db?sslmode=require
  APP_PORT: "3002"
  APP_HOST: apps-ms-service.default.svc.cluster.local
  COURSE_PORT: "3004"
  COURSE_HOST: courses-ms-service.default.svc.cluster.local
  PAYMENT_PORT: "3006"
  PAYMENT_HOST: payments-ms-service.default.svc.cluster.local

