@base_url=http://localhost:3000

POST {{base_url}}/payments/create-payment-session
Content-Type: application/json

{
  "orderId": "DJXI_33",
  "currency": "usd",
  "items": [
    {
      "name": "Product 1",
      "price": 5.000,
      "quantity": 3
    }
  ]
  
}