apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      labels:
        app: users-ms
    spec:
      containers:
        - name: users-ms
          image: gcr.io/wired-climate-442121-i1/users-ms:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: env-config
---
apiVersion: v1
kind: Service
metadata:
  name: users-ms-service
spec:
  type: ClusterIP
  selector:
    app: users-ms
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  USER_PORT: "3001"
  USER_HOST: "0.0.0.0"
  JWT_SECRET: servicio de autenticación
  DATABASE_URL_USER: postgresql://appsdb_owner:DkY8uORBLC7N@ep-blue-sea-a5lcg70b.us-east-2.aws.neon.tech/userdb?sslmode=require
